In [81]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [82]:
dataset = pd.read_csv("./iris.csv")

In [83]:
dataset.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [84]:
data = dataset[["Sepal.Length","Sepal.Width","Petal.Length","Petal.Width"]]

In [85]:
x_train, x_test,y_train,y_test = train_test_split(data,dataset["Species"],test_size=0.2,random_state=40)

In [86]:
model = RandomForestClassifier()

In [87]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [88]:
x_test.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
38            4.4          3.0           1.3          0.2
66            5.6          3.0           4.5          1.5
115           6.4          3.2           5.3          2.3
117           7.7          3.8           6.7          2.2
89            5.5          2.5           4.0          1.3

In [89]:
y_pred = model.predict(x_test)

In [90]:
np.mean(y_test == y_pred)

1.0

In [91]:
y_pred

array(['setosa', 'versicolor', 'virginica', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'versicolor'],
      dtype=object)

In [92]:
x_train.shape

(120, 4)

In [93]:
x_test.shape

(30, 4)

In [94]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [95]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]])

In [96]:
accuracy_score(y_test,y_pred)

1.0

In [97]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [98]:
knn = KNeighborsClassifier()


In [99]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [100]:
y_pred = knn.predict(x_test)

In [101]:
np.mean(y_pred == y_test)

1.0

In [102]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]])

In [103]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [104]:
dtc = DecisionTreeClassifier()

In [105]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [106]:
y_test=dtc.predict(x_test)

In [107]:
np.mean(y_pred==y_test)

1.0

In [108]:
confusion_matrix(y_pred,y_test)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]])

In [109]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [110]:
lr = LogisticRegression()

In [111]:
lr.fit(x_train,y_train)

LogisticRegression()

In [112]:
y_pred = lr.predict(x_test)

In [113]:
np.mean(y_pred==y_test)

1.0

In [114]:
confusion_matrix(y_pred,y_test)

array([[ 8,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 10]])

In [115]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

